matthewdshepherd/moviesoutnow

package-lock.json, src/Components/LoginForm/LoginForm.css, src/Components/LoginForm/LoginForm.js, src/index.js
This PR will:
- handleChnage method to update state in loginForm
- Enable button once text is in both email AND password inputs
- Disable button is not clickable, has disabled color and shows a regular cursor
- Enabled button is clickable, has enabled color and shows pointer cursor
=> Login form

src/Components/MovieCard/MovieCard.css, src/Components/MovieCard/MovieCard.js
Add padding to border and create container for genre
=> Add padding to border and create container for genre

src/Actions/index.js, src/Components/App/App.css, src/Components/App/App.js, src/Components/CurrentUser/CurrentUser.css, src/Components/CurrentUser/CurrentUser.js, src/Components/LoginForm/LoginForm.css, src/Components/LoginForm/LoginForm.js, src/Reducers/currentUser.js
This PR will:
Create Current User Class Component
Append Current and new User to the DOM
Create sign out action to reset current user to empty object in the Store state
Hide LoginForm when new or current user is logged in
Sign Out button will sign out the user by resetting the current user to an empty array and hiding Current User info while showing login form
=> Append current user

public/index.html, src/Components/App/App.css, src/Components/App/App.js, src/Components/SignupForm/SignupForm.js
This PR fixes bug where upon a successful new user signup the Signup Modal would not go away.
=> Fix bug where successful user signup would not close signup modal

src/Components/App/App.js, src/Components/CurrentUser/CurrentUser.js, src/Components/LoginForm/LoginForm.js, src/Components/MovieCard/MovieCard.js, src/Containers/Favorites/Favorites.js, src/Thunks/addFavorite.js, src/Thunks/postUserLogin.js, src/Thunks/removeFavorite.js
This PR will:
-Fix error with adding favorites
-Fix error with removing favorites
-Change favorites fetch to occur in conjunction with user login
=> Fix favorite workflow ui

src/Components/MovieCard/MovieCard.css
This PR will:
-Give movie cards a max-width for layout aesthetics
=> Fix movie card sizing

src/Components/App/App.test.js, src/Thunks/__tests__/addFavorite.js, src/Thunks/__tests__/fetchFavorites.js, src/Thunks/__tests__/fetchGenres.js, src/Thunks/__tests__/fetchRecentMovies.js, src/Thunks/__tests__/removeFavorite.js, src/Thunks/removeFavorite.js
This PR will:
-Add tests for removeFavorite thunk: happy path
-Add test for removeFavorite thunk: sad path
=> Remove fav testing

src/Components/MoviePage/MoviePage.css, src/Components/MoviePage/MoviePage.js
This PR will style the Movie Page Component with mostly a focus on CSS and minor changes to the MoviePage.js page.
=> Style the Movie Page Component

src/Components/MovieCard/MovieCard.js, src/Thunks/clickHandler.js, src/Thunks/removeFavorite.js
This PR will:
-Add a thunk to handle the clicks in movie cards
-Fix propagation issues with movie card buttons
-Fix blank home screen error
=> Fix propagation issues with view more/favorites buttons

src/Components/MoviePage/MoviePage.css, src/Components/MoviePage/MoviePage.js
This PR will touch up the MovePage Component updating User score, votes and genres.
=> Csstouchup

src/Actions/index.js, src/Actions/index.test.js, src/Containers/Favorites/Favorites.js, src/Reducers/setFavorites.js
This PR will:
-Complete testing for application redux action creators
=> Actions testing

src/Reducers/__tests__/currentMovie.js, src/Reducers/__tests__/currentUser.js, src/Reducers/__tests__/genres.js, src/Reducers/__tests__/hasErrored.js, src/Reducers/__tests__/isLoading.js, src/Reducers/__tests__/movies.js, src/Reducers/__tests__/setFavorites.js, src/Reducers/__tests__/toggleModal.js, src/Reducers/currentMovie.js
This PR will:
-Add tests for all cases in the toggleModal reducer
=> Toggle modal testing

src/Reducers/__tests__/currentMovie.js, src/Reducers/__tests__/currentUser.js, src/Reducers/__tests__/genres.js, src/Reducers/__tests__/hasErrored.js, src/Reducers/__tests__/isLoading.js, src/Reducers/__tests__/movies.js, src/Reducers/__tests__/setFavorites.js, src/Reducers/currentMovie.js
This PR will:
-Add tests for all cases in the favorites reducer
=> Set favorites testing

src/Reducers/__tests__/currentMovie.js, src/Reducers/__tests__/currentUser.js, src/Reducers/__tests__/genres.js, src/Reducers/__tests__/hasErrored.js, src/Reducers/currentMovie.js
This PR will:
-Add tests for all cases in the hasErrored reducer
=> Has errored testing

src/Reducers/__tests__/currentMovie.js, src/Reducers/__tests__/currentUser.js, src/Reducers/__tests__/genres.js, src/Reducers/__tests__/hasErrored.js, src/Reducers/__tests__/isLoading.js, src/Reducers/currentMovie.js
This PR will:
-Add tests for all cases in the isLoading reducer
=> Is loading testing

src/Reducers/__tests__/currentMovie.js, src/Reducers/__tests__/currentUser.js, src/Reducers/__tests__/genres.js, src/Reducers/__tests__/hasErrored.js, src/Reducers/__tests__/isLoading.js, src/Reducers/__tests__/movies.js, src/Reducers/currentMovie.js
This PR will:
-Add tests for all cases in the movies reducer
=> Movies testing

src/Reducers/__tests__/currentMovie.js, src/Reducers/currentMovie.js
This PR will:
-Add tests for all cases in the currentMovie reducer
=> Current movie testing

src/Reducers/__tests__/currentMovie.js, src/Reducers/__tests__/currentUser.js, src/Reducers/currentMovie.js
This PR will:
-Add tests for all cases in the currentUser reducer
=> Current user testing

src/Reducers/__tests__/currentMovie.js, src/Reducers/__tests__/currentUser.js, src/Reducers/__tests__/genres.js, src/Reducers/currentMovie.js
This PR will:
-Add tests for all cases in the genres reducer
=> Genre reducer testing

src/Components/CurrentUser/CurrentUser.js, src/Components/LoginForm/LoginForm.js, src/Components/MovieCard/MovieCard.js, src/Thunks/addFavorite.js
This Pr will resolve issues that caused errors to show in the console.
=> Clean Up Console

src/Components/App/App.css, src/Components/App/App.js, src/Components/CurrentUser/CurrentUser.css, src/Components/CurrentUser/CurrentUser.js, src/Components/CurrentUser/CurrentUser.test.js, src/Components/LoginForm/LoginForm.js
This PR will move the home button to live below the logo on all pages. 
Update the LoginForm Component to the correct one with logic to show when password or email were entered incorrectly
=> Main page styling

src/Components/App/App.js, src/Components/App/App.test.js, src/Components/App/__snapshots__/App.test.js.snap
This PR will:
-Add tests for the App component
=> App testing

src/Components/App/App.js, src/Components/CurrentUser/CurrentUser.css, src/Components/LoginForm/LoginForm.js, src/Containers/Favorites/Favorites.js
This PR will: 
- Update Error Spelling and remove Underline from Sign out Button
=> Update Error Spelling and remove Underline from Sign out Button

src/Components/CurrentUser/CurrentUser.js
-Remove unused imports/dispatches from the component
=> Remove unused imports in current user

src/Components/App/__snapshots__/App.test.js.snap, src/Components/CurrentUser/CurrentUser.js, src/Components/CurrentUser/CurrentUser.test.js, src/Components/CurrentUser/__snapshots__/CurrentUser.test.js.snap
This PR will:
-Add test for currentUser snapshot
-Add test for currentUser mapStateToProps
=> Current user refac

src/Components/MovieCard/MovieCard.js, src/Components/MoviePage/MoviePage.js
This Pr will refactors specific movie link to not need button wrapped around it.
=> refactors specific movie link to not need btn wrapped around it

src/Thunks/__tests__/addFavorite.js, src/Thunks/__tests__/clickHandler.js
This PR will:
-Add test for click handler thunk
-Fix tests for add favorite thunk
=> Thunk test refac
